// petclinic dev or main
pipeline {

    parameters {
       choice(name: "environment_project", choices: ["dev", "main"], description: "Environment dir to use for deployment")
       choice(name: "environment_code", choices: ["dev", "main"], description: "Environment dir to use for deployment")
    }
   environment {
    JAVA_HOME='/opt/jdk-19.0.1'
   }
   agent  { label 'maven' }
   tools {  maven 'mvn'   }
        options {
                timestamps ()
            }
    stages {
        /*stage('Git checkout project') {
            steps {
                 script{
                        echo '=== start Git chekout project ==='
                        dir("project")
                        {
                            git branch: '${environment_project}', credentialsId: 'jenkis-git-key', url: 'git@github.com:WladimirRogovenko/petclinic-CICD.git'
                        }
                        echo '=== end Git chekout project ==='
                    }
                }
            }
        */
        stage('Git checkout petclinic source') {
            steps {
                 script{
                        echo '=== start Git chekout petclinic source ==='
                        dir("petclinic")
                        {
                            git branch: '${environment_code}', credentialsId: 'jenkis-git-key', url: 'git@github.com:WladimirRogovenko/petclinic.git'
                        }
                        echo '=== end Git chekout petclinic source ==='
                    }
                }
            }
        stage('Build') {
            steps {
                script {
                    echo '=== start build petclinic  ==='
                    sh 'whereis mvn'
                    echo 'local version mvn'
                    sh 'mvn --version'
                    sh "pwd;cd petclinic; pwd; mvn package"
                    echo '=== end build petclinic ==='
                }
               }
            }
        stage ('Tests') {
            steps {
              echo 'some tests must be here ))'  
            }
        }
        stage ('Archive') {
            steps {
              echo '=== start archiving artifacts petclinic  ==='
              //archiveArtifacts artifacts: 'petclinic/target/*.jar', followSymlinks: false  
              archiveArtifacts artifacts: '**/target/*.jar', followSymlinks: false, fingerprint: false
              echo '=== end archiving artifacts petclinic  ==='
            }
        }
        /*
        stage('Run') {
            steps {
               script {
                echo '=== start run petclinic  ===' 
                echo 'java version'
                sh 'java --version'
                echo "$JAVA_HOME/bin java version"
                sh "$JAVA_HOME/bin/java --version"
                sh "pwd;cd petclinic; pwd; $JAVA_HOME/bin/java -jar target/*.jar --server.port=8081" 
                echo '=== end run petclinic ==='
                //sleep(60)
                }
               }
            }
        */            
        }
    }