version: '3'

services:
  app:
    image: spring-openjdk:1.3
    ports:
      - 8082:8082
      - 80:80
    volumes:
      - /home/ubuntu/app:/opt/app:ro
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/petclinic"

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "/home/ubuntu/petclinic/mysql_db/conf.d:/etc/mysql/conf.d"
      - "/home/ubuntu/petclinic/mysql_db/mysql:/var/lib/mysql"
